### ISSUE TITLE
Update wording in regards to "public API"

### ISSUE THREAD

**Issue by slabe-svetlo** [ThreatConnect-Inc/threatconnect-developer-docs#222]
### Description:
From this text: "The public, ThreatConnect API is accessible at https://api.threatconnect.com."

Some may think there is a public, as in free API for us to use, even though the process to create an API user is above. Suggest  a rewording along the lines of:

"For those with a ThreatConnect public cloud account and API user, the ThreatConnect API is accessible at https://api.threatconnect.com."

### Link(s):
- https://docs.threatconnect.com/en/latest/rest_api/quick_start.html#using-the-api

**Comment by fhightower** [comment]
Thanks @slabe-svetlo !
