### ISSUE TITLE
Add Workaround for tclib Under macOS Homebrew Python

### ISSUE THREAD

**Issue by utkonos** [ThreatConnect-Inc/threatconnect-developer-docs#226]
### Description:
There is a known bug in pip that means a setup.cfg file is needed in the app folder during the build process for the process to succeed.

The following section of the docs needs a red warning callout box that includes instructions for macos homebrew python and adding a setup.cfg with the following contents in the same directory as requirements.txt:
```
[install]
prefix=
```
https://docs.threatconnect.com/en/latest/tcex/building_apps.html#build-local-modules

It should also include the source link for the workaround so users can read more about the root cause:
https://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both

**Comment by fhightower** [comment]
Thanks! This will be fixed once https://github.com/ThreatConnect-Inc/tcex/pull/27 is merged.
