### ISSUE TITLE
Batch file upload documentation for size and file occurrences

### ISSUE THREAD

**Issue by kdeltared** [ThreatConnect-Inc/threatconnect-developer-docs#252]
### Description:
It would be awesome to have documentation on how to set size and file occurrences while using batch upload for file indicators. I'm trying to do it but I cannot achieve it.

![image](https://user-images.githubusercontent.com/14323062/41746562-2a291d5e-7581-11e8-9638-98334c5af596.png)

### Link(s):
- https://docs.threatconnect.com/en/latest/rest_api/indicators/indicators.html#batch-indicator-input-file-format

**Comment by fhightower** [comment]
Hi @kdeltared! Thanks for raising this issue.

Currently, our batch API does not support file sizes and file occurrences, although there are plans to add this functionality in the future.

**Comment by fhightower** [comment]
@kdeltared : We've released a new batch API in ThreatConnect version 5.6 that allows for the creation of file size and occurrences. We'll add some documentation on this soon.

**Comment by kdeltared** [comment]
Nice! Thank you!
