### ISSUE TITLE
load_attributes 

### ISSUE THREAD

**Issue by turnipseeed** [ThreatConnect-Inc/threatconnect-developer-docs#260]
### Description:
When trying to load attributes for an incident in ThreatConnect there is an error stating the ID must be an integer. See attached in image. This code had previously run for ~6 months. Below is the function from which the error is generated 

def download_incidents_threats(self,incidents):
        '''
        Given Threat Connect documents download and place into the Upload Folder.
        '''
        # iterate through the retrieved incidents or threats
        for i in incidents:
            print i
            # doc_file1 and temp_title1 for html
           def download_incidents_threats(self,incidents):
        '''
        Given Threat Connect documents download and place into the Upload Folder.
        '''
        # iterate through the retrieved incidents or threats
        for i in incidents:
            print i
            # doc_file1 and temp_title1 for html
            **i.load_attributes()**
            temp_title1 = re.sub('[^A-Za-z0-9\.\-\_]+',' ',i.name) + ".html"
            doc_file1 = os.path.join("Upload",temp_title1)
            with open(doc_file1, 'w') as f:
                for attribute in i.attributes:
                    for a in str(attribute.value).split("\n"):
                        f.write("<p>{}</p>".format(a))
            temp_title1 = re.sub('[^A-Za-z0-9\.\-\_]+',' ',i.name) + ".html"
            doc_file1 = os.path.join("Upload",temp_title1)
            with open(doc_file1, 'w') as f:
                for attribute in i.attributes:
                    for a in str(attribute.value).split("\n"):
                        f.write("<p>{}</p>".format(a))

![Error with incident (i) printed](https://user-images.githubusercontent.com/48841283/54849308-db14b300-4cb1-11e9-9d0b-982b577e7822.PNG)

### Link(s):
-

**Comment by Raymc007** [comment]
@turnipseeed : Python SDK has been deprecated. Please use tcex.
