### ISSUE TITLE
[API docs] Add docs detailing how to upload reports via API

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/threatconnect-developer-docs#272]
### Description:

It would be helpful to add docs detailing how to upload reports via API. This could be accomplished by updating the docs for uploading content to a document group (https://docs.threatconnect.com/en/latest/rest_api/groups/groups.html#uploading-document-contents and https://docs.threatconnect.com/en/latest/rest_api/groups/groups.html#update-document-contents).

**Comment by brikardtc** [comment]
@fhightower I'm unsure what you are meaning here as both of those link to: https://docs.threatconnect.com/en/latest/rest_api/groups/groups.html#update-document-contents which are the steps to follow to upload a report/documents contents as you must first make the request, then in the reply to that request you will receive the document/report ID which you then POST the file contents to using those instructions.

EX:
First the POST to create the group Document/Report:
**POST** _/v2/groups/documents_ or **POST** _/v2/groups/reports_
**Header:** Content-type: application/json; charset=utf-8
**Body:**
```
{
  "fileName" : "my_report.doc",
  "name": "Document or Report that will displayed as the Group name",
}
```
or if Malware the Body will be:
```
{
  "fileName" : "malwaresample.zip",
  "name": "Document name that will displayed as the Group name",
  "malware": true,
  "password": "TCinfected"
}
```

Which will respond back with a JSON response like:
```
{
    "status": "Success",
    "data": {
        "document": {
            "id": 181719,
            "name": "Document or Report that will displayed as the Group name",
            "owner": {
                "id": 92,
                "name": "My Org",
                "type": "Organization"
            },
            "dateAdded": "2019-12-26T21:07:26Z",
            "webLink": "https://threatconnect/auth/document/document.xhtml?document=181719",
            "fileName": "my_report.doc",
            "status": "Awaiting Upload"
        }
    }
}
```

You would take the groupID, in this case, data.document.id (181719) and put it into the following:

Then:
**PUT**  _/v2/groups/{documents or reports}/{groupID}/upload_
Content-Type: application/octet-stream
**Body:** {binary_file} 


Can you clarify for us what you are looking for?

**Comment by fhightower** [comment]
@brikardtc : Thanks for the response and sorry about being unclear. I suggest adding documentation on how to upload reports. Currently, all of the documentation deals with how to upload content to Document groups, but I would like to upload to Report groups. From you example and past experience, I understand the process of uploading content is the same for Documents and Reports, but I think it would be helpful to make this explicit in the docs. Does that make sense?

**Comment by brikardtc** [comment]
#280 created to address. Thanks for the clarification.
