### ISSUE TITLE
[App config file docs] Improve docs for making keychain variables available as valid values

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/threatconnect-developer-docs#273]
In an app's config file, it is possible to provide the keychain variables as valid values like: `${USER:KEYCHAIN}` and `${ORGANIZATION:KEYCHAIN}` and `${SYSTEM:KEYCHAIN}`. Please add these options to the docs for external variables: https://docs.threatconnect.com/en/latest/deployment_config.html#external-variables .

**Comment by brikardtc** [comment]
@fhightower I've created PR #277 to address this issue. However, I've _intentionally_ left off $SYSTEM:{TYPE} as you do not have the ability to create SYSTEM level TEXT/KEYCHAIN/FILE variables.

**Comment by fhightower** [comment]
Perfect, thanks @brikardtc !
