### ISSUE TITLE
Link at Open the ThreatConnect API Postman collection doesn't work.

### ISSUE THREAD

**Issue by JanoutV** [ThreatConnect-Inc/threatconnect-developer-docs#291]
### Description:
Hello team, When I try to follow the Postman Configuration [doc](https://docs.threatconnect.com/en/latest/rest_api/v3/postman_config.html#) the link highlighted at this text for getting to your collection: `Open the ThreatConnect API Postman collection.` doesn't work for me:

https://god.gw.postman.com/run-collection/19334095-d4755fea-88fd-4847-ac1f-054f762e193f?action=collection%2Ffork&collection-url=entityId%3D19334095-d4755fea-88fd-4847-ac1f-054f762e193f%26entityType%3Dcollection%26workspaceId%3D6ac46ed6-4579-4d30-ab95-5cdc6625680b

I get presented with the correct page:
![image](https://github.com/ThreatConnect-Inc/threatconnect-developer-docs/assets/44194415/f0301dad-0f71-455b-b8ea-a8a82f64cef2)
however when I try to view it, or click the `Fork Collection` I am presented with the following screen:

![image](https://github.com/ThreatConnect-Inc/threatconnect-developer-docs/assets/44194415/729f3caf-004d-4bf6-a182-d54da3b36bfb)

I was eventualy able to find the collection here: https://www.postman.com/threatconnect-api-dev/workspace/threatconnect-v3-api/overview -> but I think this is something you want to fix for other users :)

Regards,

Vladimir

P.S. -> the file handling this is `docs/rest_api/v3/postman_config.rst`

**Comment by moblack-tc** [comment]
@JanoutV:

Thank you for bringing this issue to our attention! I updated that section of the API documentation to include a functioning link to the ThreatConnect v3 API Postman collection.

Please let me know if you have any questions or come across any other issues with the documentation. Thanks!

Mark O'Black
Technical Writer | ThreatConnect
moblack@threatconnect.com

**Comment by JanoutV** [comment]
Will do. Thanks for fixing the issue!
